# Generated by Django 5.2.6 on 2025-10-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectordb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulevectorstore',
            name='persistence_directory',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
