# Generated by Django 5.2.6 on 2025-10-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectordb', '0002_question_answer_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='feedback_text',
            field=models.TextField(blank=True),
        ),
    ]
