# Generated by Django 5.2.6 on 2025-09-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
