# Generated by Django 5.2.6 on 2025-10-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0002_document_file_alter_document_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='persist_directory',
            field=models.CharField(default='5c949c4c9fb211f0bda2a8934a854fcb', max_length=255),
        ),
    ]
