# Generated by Django 5.2.6 on 2025-10-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0003_alter_project_persist_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, help_text='File extension', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='persist_directory',
            field=models.CharField(default='b2746b40a00e11f0bda2a8934a854fcb', max_length=255),
        ),
    ]
