# Generated by Django 5.2.6 on 2025-10-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0004_document_file_size_document_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='persist_directory',
            field=models.CharField(default='76d342b4a1c111f0bda2a8934a854fcb', max_length=255),
        ),
    ]
