# Generated by Django 5.2.6 on 2025-10-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0006_alter_project_persist_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='persist_directory',
            field=models.CharField(default='046cf58ca1dd11f0bda2a8934a854fcb', max_length=255),
        ),
    ]
